### PR TITLE
🏷 Release 1.3.0

### PR DESCRIPTION
**Pull request by dankolbman**
# Kids First Dataservice Release 1.3.0

## Features

Adds several new fields in the datamodel in #408:

- `family_type` on Family
- `source_text_notes` on FamilyRelationship
- `affected_status` on Participant
- `diagnosis_category` on Participant
- `visible` on all tables

### Summary

Feature Emojis: ✨x4 👷x1 🔧x1 🐛 x1
Feature Labels: [data model](https://api.github.com/repos/kids-first/kf-api-dataservice/labels/data%20model) x4 [devops](https://api.github.com/repos/kids-first/kf-api-dataservice/labels/devops) x3 [feature](https://api.github.com/repos/kids-first/kf-api-dataservice/labels/feature) x3

### New features and changes

- (#416) 🐛 Fix biospecimens and diagnoses links by diagnosis_id and biospecimen_id - @parimalak
- (#413) 👷 Load bucket url from vault - @dankolbman
- (#401) ✨ Add biospecimen_diagnosis association table - @parimalak
- (#410) 🔧 Increase nginx proxy_buffer size to stop truncating repsonses - @dankolbman
- (#408) ✨Data model changes - @parimalak
- (#407) ✨ Add visible to base model - @parimalak
- (#394) ✨ Add biospecimen_genomic_file association table and endpoints - @parimalak

### CODE REVIEW

**Comment by parimalak** [comment]
I think we missed biospecimen-genomic file commits

**Comment by dankolbman** [comment]
Added

**Comment by junjun-zhang** [comment]
From ES model point of view, all of the new fields are included in the new ES model, except for `source_text_notes` on FamilyRelationship table. If this field need to be exposed in the portal, we will need to add it in the ES model.

**Comment by dankolbman** [comment]
Thanks for the review @junjun-zhang !
I believe adding the field to the datamodel won't be a blocker to the etl or the portal, will it?
We can always expose it in later releases of the mapping and portal, if we wish (although the field is largely empty atm)

**Comment by junjun-zhang** [comment]
@dankolbman you are right, the es model is not a block for this for sure. If we do need `source_text_notes` on FamilyRelationship to be included in ES, it can be done at any point.

**Review by znatty22 — APPROVED** [review]
💯

**Review by allisonheath — APPROVED** [review]

**Comment by baileyckelly** [comment]
Also spoke with SBG over slack in the Data Service channel. Olga Sebez said they've seen the changes and every thing is OK on their side.

**Review by baileyckelly — APPROVED** [review]
I'm aware of all these changes from a PM standpoint. Also spoke with SBG over slack in the Data Service channel. Olga Sebez said they've seen the changes and every thing is OK on their side.

**Review by rosibaj — APPROVED** [review]
changes captured in this es release: 

https://github.com/kids-first/kf-es-model/releases/tag/v0.5.0

**Pull request merged**
