### PR TITLE
🐛 fix backref's for diagnoses, outcomes, phenotypes in participant model

### PR DESCRIPTION
**Pull request by parimalak**

### CODE REVIEW

**Review by znatty22 — APPROVED** [review]
💯

**Review by dankolbman — COMMENTED** [review]
Should we set `uselist=False`?? on the backref?

**Comment by parimalak** [comment]
isn't `uselist=False` lets only single value which is not desired for us as participant expects list of `phenotypes` or `outcomes` ?

**Comment by dankolbman** [comment]
Not if it's inside the backref: `backref=db.backref('participant', uselist=False, lazy=True)`

**Comment by znatty22** [comment]
@parimalak we do want the backref to be singular because phenotype reference one participant, outcome references one participant, etc. Going the other way, participant has many phenotypes, many outcomes, etc. 

@dankolbman I don't think you need to specify `uselist=False` here because sqlalchemy knows this is a one to many relationship (since there is a foreign key on the child) and the backref is referring to the many to one relationship. `uselist` is set to False by default.

**Review by dankolbman — APPROVED** [review]

**Pull request merged**
