### PR TITLE
 💬 add linked longread 10x sequencing strategy

### LINKED ISSUE #499: new sequencing strategy needed
"Linked-Read WGS (10x Chromium)" per https://github.com/kids-first/kf-study-imports/issues/374

### PR DESCRIPTION
**Pull request by fiendish**
Fixes #499

### CODE REVIEW

**Review by dankolbman — APPROVED** [review]
Lgtm. 

Was running into some issues that was making me think that we need to refactor these enums into their own table or even just an enum type, but that's another issue

**Review by znatty22 — COMMENTED** [review]
👍

**Comment by fiendish** [comment]
> 👍

✅ ?

**Comment by znatty22** [comment]
@fiendish  Oh haha sorry, I always do that. I meant to click approve

**Review by znatty22 — APPROVED** [review]

**Review by parimalak — APPROVED** [review]

**Pull request merged**
