### PR TITLE
✨ Exclude fkey lists from genomic-files and biospecimens results

### PR DESCRIPTION
**Pull request by parimalak**
Address #509 
Removes this list:
Screen Shot 2019-04-11 at 2 52 02 PM

### CODE REVIEW

**Review by znatty22 — CHANGES_REQUESTED** [review]
What's the motivation for this?

**Comment by parimalak** [comment]
@znatty22 When we query cohort genomic files etc. the list is large and taking up the entire space  if accessed in browser; we get the links any way using _links. and also, other tables are excluded and accessible only through links.

**Review by znatty22 — APPROVED** [review]
👍 

I bet this will improve performance on requests to get a page of biospecimens/genomic files

**Review by fiendish — APPROVED** [review]

**Review by dankolbman — APPROVED** [review]
Good catch. We should probably add tests for field exclusions sometime in the future to make sure we aren't doing this elsewhere.

**Pull request merged**
