### PR TITLE
✨update outcome enum to deceased

### PR DESCRIPTION
**Pull request by parimalak**

### CODE REVIEW

**Comment by dankolbman** [comment]
Does there need to be a data migration for this?

**Comment by dankolbman** [comment]
Looks like there's 977 values that will need to be updated.

**Comment by parimalak** [comment]
ya, I thought we can patch it without doing the migration because it is just data change without any model change.

**Review by dankolbman — APPROVED** [review]

**Review by znatty22 — APPROVED** [review]
👍 Looks good

**Pull request merged**
