### PR TITLE
✨ Add new SE, GF columns for Bix

### PR DESCRIPTION
**Pull request by znatty22**
## Todo

- [x] Push migrations
- [x] Update workflow_type enum with values from Bix

### CODE REVIEW

**Review by yuankunzhu — APPROVED** [review]
the field names lgtm for now. created #651 to update enum values

**Comment by HuangXiaoyan0106** [comment]
@znatty22 We have updated the [kf_pipeline_outputs.csv](https://github.com/d3b-center/bixops-dataset-process/blob/master/docs/pipeline_outputs/kf_pipeline_outputs.csv) file.
- current workflow `workflow_type` enum
```
    Alignment
    Family-Joint-Genotyping
    GATK-HaplotypeCaller-gVCF
    Germline-Mutation
    Long-Reads-Mutation
    RNAseq-Analysis
    Single-VCF-Genotyping
    Somatic-Mutation
```
- current workflow `data_type` enum
```
    Adapter Stats
    Alignment Metrics
    Alignment Stats
    Alignment Summary
    Alternative Splicing
    Annotated Gene Fusion
    Annotated Germline Structural Variation
    Annotated Somatic Copy Number Segment
    Annotated Somatic Mutation
    Annotated Somatic Mutation Index
    Annotated Variant Call
    Annotated Variant Call Index
    Artifact Metrics
    Chimeric Aligned Reads
    Consensus Somatic Mutation
    Consensus Somatic Mutation Index
    Contamination Estimation
    Control Copy Number
    Control Copy Number Segment
    Cutadapter Metrics
    Extra-Chromosomal DNA
    Familial Relationship
    Familial Relationship Report
    GC Metrics
    Gender Metrics
    Gender QC Metrics
    Gene Expression Count
    Gene Expression Quantification
    Gene Level Copy Number
    Genome Aligned Reads
    Genome Aligned Reads Index
    Genomic Variant
    Genomic Variant Index
    Het Call QC Metrics
    Insert Size Metrics
    Isoform Expression Quantification
    Masked Consensus Somatic Mutation
    Masked Consensus Somatic Mutation Index
    Masked Somatic Mutation
    Masked Somatic Mutation Index
    Pre-pass Somatic Structural Variation
    Pre-pass Somatic Structural Variation Index
    QC Metrics
    Quality Score Distribution
    RNAseq Alignment Metrics
    Raw Gene Fusion
    Raw Germline Structural Variation
    Raw Germline Structural Variation Index
    Raw Simple Somatic Mutation
    Raw Simple Somatic Mutation Index
    Raw Somatic Copy Number Segment
    Raw Somatic Structural Variation
    Raw Somatic Structural Variation Index
    Recalibration Report
    Reference Copy Number Profiling
    Relatedness QC Metrics
    Somatic Copy Number BAF
    Somatic Copy Number Diagram
    Somatic Copy Number Metrics
    Somatic Copy Number Ratio
    Somatic Copy Number Scatter
    Somatic Copy Number Segment
    Somatic Copy Number Subclone Segment
    Somatic Copy Number Variation
    Somatic Structural Variation
    Splice Junction
    Tool Log
    Tumor Copy Number
    Tumor Copy Number Segment
    Tumor Ploidy and Purity
    Tumor Purity
    Variant Calling Metrics
    WGS Metrics
    WXS Metrics
```

**Comment by HuangXiaoyan0106** [comment]
@znatty22 It seems you didn't update the `data_type` enum, like `Metric -> Metrics`, `Read -> Reads `, as I listed.
 or you will create a new PR for this?

**Comment by znatty22** [comment]
> @znatty22 It seems you didn't update the `data_type` enum, like `Metric -> Metrics`, `Read -> Reads `, as I listed. or you will create a new PR for this?

@HuangXiaoyan0106 This requires a bigger effort because we have to ensure that none of the existing data uses old values before we get rid of them or we have to do a data migration. Since this is a bigger effort and different from adding new fields, I think it should be in a separate PR

**Comment by yuankunzhu** [comment]
> > @znatty22 It seems you didn't update the `data_type` enum, like `Metric -> Metrics`, `Read -> Reads `, as I listed. or you will create a new PR for this?
> 
> @HuangXiaoyan0106 This requires a bigger effort because we have to ensure that none of the existing data uses old values before we get rid of them or we have to do a data migration. Since this is a bigger effort and different from adding new fields, I think it should be in a separate PR

@znatty22 @HuangXiaoyan0106 we don't have to get rid of the old enum, I think for now, we just wanna make sure we have all the new enum added for the "data_type"

**Pull request merged**
