### PR TITLE
✏️ relationhips -> relationships

### LINKED ISSUE #366: Family relationships link is mispelled
When retrieving a participant(s), the family relationship link in the `_links` part of the response is misspelled. It is spelled as "family_relationhips" and should be spelled as "family_relationships"

```
_links: {
biospecimens: "/biospecimens?participant_id=PT_9KYB7NF2",
collection: "/participants",
diagnoses: "/diagnoses?participant_id=PT_9KYB7NF2",
family: "/families/FM_094W8WAR",
family_relationhips: "/family-relationships?participant_id=PT_9KYB7NF2",
outcomes: "/outcomes?participant_id=PT_9KYB7NF2",
phenotypes: "/phenotypes?participant_id=PT_9KYB7NF2",
self: "/participants/PT_9KYB7NF2",
study: "/studies/SD_46SK55A3"
}
```

### PR DESCRIPTION
**Pull request by fiendish**
fixes #366

### CODE REVIEW

**Review by znatty22 — CHANGES_REQUESTED** [review]
Yay thank you for fixing! Got a couple minor requests..
- Can you fix the pep8 error? See CircleCI details link for the line # thats causing it
- Can you go into tests/test_api.py and make a mod to the test parameters for the test_child_links test? Add `family_relationships` to the list of participant relations.
Should be [line 124](https://github.com/kids-first/kf-api-dataservice/blob/212a49c247e5d4198deea1593446962566ad594b/tests/test_api.py#L124)

We never caught this bug bc i forgot to put the test in for family relationships :(

**Comment by fiendish** [comment]
👌

**Review by znatty22 — APPROVED** [review]
👍

**Comment by dankolbman** [comment]
Can you rebase on master? We like to avoid having a large log of merges into master in our commit history.

**Comment by fiendish** [comment]
👌

**Review by dankolbman — APPROVED** [review]
💯

**Pull request merged**
