### PR TITLE
🐛 Update README

### PR DESCRIPTION
**Pull request by znatty22**
Add pip install -e . line to readme

### CODE REVIEW

**Comment by dankolbman** [comment]
`manage` also works

**Comment by znatty22** [comment]
Hmm ok, I could've sworn it didn't work for parimala when she ran one of the flask commands but maybe something else was wrong

**Comment by dankolbman** [comment]
It will work if the module is installed. This brings up a point that we should probably rename `manage.py` or maybe move it into `dataservice/__init__.py` so it doesn't appear that the application is named `manage`.

**Comment by znatty22** [comment]
Ok, so then should we add `pip install -e .` to the README.md?

**Comment by dankolbman** [comment]
Yeah, I think that's better as that's how it's done in the dockerfile and jenkins.

**Pull request closed without merging**
