### PR TITLE
🐛 Fix #295 , 500 server errors on POST to sequencing-centers.

### LINKED ISSUE #295: POST to sequencing-centers produces error 500
```
curl -XPOST -H "Content-Type: application/json" http://localhost:5000/sequencing-centers -d '{"kf_id": "SC_K52V7463", "name": "Washington University"}'
```
Causes the server to:
```
127.0.0.1 - - [03/May/2018 10:13:33] "POST /sequencing-centers HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/Users/kelmana/Documents/kids-first/kf-api-dataservice/dataservice/api/sequencing_center/resources.py", line 69, in post
    body
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/marshmallow_sqlalchemy/schema.py", line 187, in load
    return super(ModelSchema, self).load(data, *args, **kwargs)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/marshmallow/schema.py", line 580, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/marshmallow/schema.py", line 685, in _do_load
    original_data=data)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/marshmallow/schema.py", line 858, in _invoke_load_processors
    data=data, many=many, original_data=original_data)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/marshmallow/schema.py", line 960, in _invoke_processors
    data = utils.if_none(processor(data), data)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/marshmallow_sqlalchemy/schema.py", line 169, in make_instance
    instance = self.instance or self.get_instance(data)
  File "/Users/kelmana/anaconda3/lib/python3.6/site-packages/marshmallow_sqlalchemy/schema.py", line 154, in get_instance
    return self.session.query(
AttributeError: 'DummySession' object has no attribute 'query'
```

PR with fix incoming.

### PR DESCRIPTION
**Pull request by fiendish**
Fixes #295 ,  500 server errors on POST to sequencing-centers.
See https://github.com/marshmallow-code/flask-marshmallow/issues/44

### CODE REVIEW

**Comment by dankolbman** [comment]
What was the error being thrown here? Can it be reproduced + tested?

**Comment by fiendish** [comment]
Both sides of the error are described in #295 
But to reproduce you can throw `curl -XPOST -H "Content-Type: application/json" http://kf-api-dataservice-qa.kids-first.io/sequencing-centers -d '{"kf_id": "SC_K52V7463", "name": "Washington University"}'` into your terminal and see the error come back.

**Comment by dankolbman** [comment]
Hmm ok, I'm guessing this is due to the fact that it needs to make a query in the serializer to ensure that the name is unique

**Review by dankolbman — APPROVED** [review]
💯 
Remember to rebase on master manually first before merging.

**Comment by znatty22** [comment]
I was able to reproduce it locally. So we may want to hold off on merging this PR and make another PR to address the larger problem. I've confirmed that this happens any time you try to POST any entity with a given kf_id. Also, not sure about this but I think we may need to add in some validation on kf_ids (ensuring that the correct prefixes exist depending on the entity). We may as well do that all in one PR

**Comment by dankolbman** [comment]
I see. Looks like maybe we wanted to include a `kf_id` for dump only in the base schema: https://github.com/kids-first/kf-api-dataservice/blob/master/dataservice/api/common/schemas.py#L23

We may want to change this, though, for #293 and #294

**Comment by dankolbman** [comment]
#308 is a general fix for this problem.

**Comment by dankolbman** [comment]
Fixed by #308

**Pull request closed without merging**
