### PR TITLE
✨ add data_type enums of bix workflows

### PR DESCRIPTION
**Pull request by chris-s-friedman**
adds enums from bix workflows so that outputs of intermediate steps of bix workflows can be registered

### CODE REVIEW

**Review by liberaliscomputing — DISMISSED** [review]

**Review by zhangb1 — APPROVED** [review]
looks good. covered all the new data type we added

**Comment by liberaliscomputing** [comment]
I have a few comments/concerns:

1. Controlled Vocabulary
This PR brings in numerous enumerated values and are they extracted from an authoritative source(s) of terminology? On the [Notion page](https://www.notion.so/d3b/6175c0651e9743b998d084f18a9aa54f?v=92b3d90a0ffe4be6bb7dc719219a99c4), I don't see any references and this may overburden us with additional harmonization effort when ingesting into FHIR or sharing with other institutions (say external collaborators submit data) **IF** this new value set is our own custom product. We should avoid creating a custom value set unless otherwise necessary.

2. Value Migration
I am seeing lots of previously existing values got subdivided into multiple values. For example,
`Gene Fusions` >> `Gene Fusions`, `Annotated Gene Fusion`, and `Raw Gene Fusion`. Do we have a proper migration plan for this?

3. Term Uniformity
As shown above, some of these values are singular wheres the others are plural. This is maybe because BIXU didn't use a controlled terminology?

**Review by liberaliscomputing — CHANGES_REQUESTED** [review]
I have a few comments/concerns:

1. Controlled Vocabulary
This PR brings in numerous enumerated values and are they extracted from an authoritative source(s) of terminology? On the [Notion page](https://www.notion.so/d3b/6175c0651e9743b998d084f18a9aa54f?v=92b3d90a0ffe4be6bb7dc719219a99c4), I don't see any references and this may overburden us with additional harmonization effort when ingesting into FHIR or sharing with other institutions (say external collaborators submit data) **IF** this new value set is our own custom product. We should avoid creating a custom value set unless otherwise necessary.

2. Value Migration
I am seeing lots of previously existing values got subdivided into multiple values. For example,
`Gene Fusions` >> `Gene Fusions`, `Annotated Gene Fusion`, and `Raw Gene Fusion`. Do we have a proper migration plan for this?

3. Term Uniformity
As shown above, some of these values are singular wheres the others are plural. This is maybe because BIXU didn't use a controlled terminology?

**Comment by chris-s-friedman** [comment]
@allisonheath @baileyckelly or @yuankunzhu can you comment on @liberaliscomputing point 1: 

>1. Controlled Vocabulary
This PR brings in numerous enumerated values and are they extracted from an authoritative source(s) of terminology? On the [Notion page](https://www.notion.so/d3b/6175c0651e9743b998d084f18a9aa54f?v=92b3d90a0ffe4be6bb7dc719219a99c4), I don't see any references and this may overburden us with additional harmonization effort when ingesting into FHIR or sharing with other institutions (say external collaborators submit data) IF this new value set is our own custom product. We should avoid creating a custom value set unless otherwise necessary.

For 2

> 2. Value Migration
I am seeing lots of previously existing values got subdivided into multiple values. For example,
Gene Fusions >> Gene Fusions, Annotated Gene Fusion, and Raw Gene Fusion. Do we have a proper migration plan for this?

I don't think there is a plan to migrate existing things. @zhangb1 can confirm my _understanding_: that these mappings are additive and nothing already registered would need to have data type changed. @zhangb1 or @yuankunzhu can also confirm my understanding: that these new enums are different from pre-existing ones. 

for 3:

> 3. Term Uniformity
As shown above, some of these values are singular wheres the others are plural. This is maybe because BIXU didn't use a controlled terminology?

@zhangb1 maybe we can review the new terms for uniform values, so that the ones you use match the terms we use in the dataservice?

**Comment by allisonheath** [comment]
@liberaliscomputing other than GDC/ICGC (which I believe our teams created most of this terminology) I'm not aware of any other terminology we could leverage. I think unless you have another suggestion, let's just move forward with this? I'd imagine we would make this a CodeSet in FHIR ultimately. 

As discussed with @yuankunzhu we do want all of the terms to be singular (unless there's a good reason to be plural - in which case we should document it). Once we adjust that - I think it's good to merge.

**Comment by liberaliscomputing** [comment]
@allisonheath, I was also unable to find an authoritative terminology for this when working on building a genomics profile in FHIR. If we are truly a frontier in this domain, then yes, this should be our novel contribution to FHIR with ValueSet and CodeSystem. This is not necessarily, but if we can have a few external reviews on this enumerated value set, that would be great though (if time-sensitive, just ignore this idea).

**Comment by liberaliscomputing** [comment]
@chris-s-friedman, if we control singular vs plural as @allisonheath suggested to @yuankunzhu, we would need to migrate the current values in Dataservice.

**Comment by chris-s-friedman** [comment]
@liberaliscomputing this is time-sensitive. Is a potential course of action here to 

1. add the new, singular-form data types and singular-forms of the old data types in this PR
2. I do time sensitive work registering files with new (singular) data types
3. in a separate PR we remove the old plural data types and perform the migration?

**Comment by allisonheath** [comment]
@chris-s-friedman that sounds like a reasonable course of action to me

**Review by liberaliscomputing — APPROVED** [review]

**Pull request merged**
