### PR TITLE
🐛 Use correct capitalization for more than one race

### PR DESCRIPTION
**Pull request by parimalak**

### CODE REVIEW

**Review by fiendish — APPROVED** [review]
Looks great. 

Can you also add it to https://github.com/kids-first/kf-api-dataservice/blob/51a821c9971b3e229e0b9555b8669fd9bde87acb/dataservice/util/data_gen/data_generator.py#L57

😃

**Comment by parimalak** [comment]
Data generator script got obsolete. We are no longer updating all changes  because of complexity of relations and use cases.

**Comment by fiendish** [comment]
Gotcha. Fine by me.

**Review by znatty22 — APPROVED** [review]
👍

**Comment by dankolbman** [comment]
What is the plan for retroactively migrating these values?

**Comment by parimalak** [comment]
Right now ETL taking care of the updates as we are persisting kf_id/s study wise. if multiple studies needs to be updated; we might have to think through how often we are going to acknowledge these changes. Based on that we can run study specific etl or a separate script/s to update values.

**Pull request merged**
